version: '3'

services:
  game-server:
    image: llmctf/2024q-cry-cbc:latest
    networks:
      ctfnet:
        aliases:
          - crypto.chal.csaw.io
    ports:
      - 9996:9996

networks:
  ctfnet:
    external: true